### PR TITLE
Add a MOSQUITO_REDIS_URL Env Variable by default

### PR DESCRIPTION
**Pull request by irlcatgirl**
The default REDIS_URL might be used by conflicting dependencies, or a app may wish to have a dedicated instance for background jobs. This pull request changes mosquito's behavior to check for a "MOSQUITO_REDIS_URL" ENV Var before using the "REDIS_URL" ENV Var.

### CODE REVIEW

**Comment by robacarp** [comment]
Hi @nsuchy thanks for the pull request. Ideally I'd like to ditch the magic URL altogether, as indicated by #3. What do you think about that?

**Comment by nsuchy** [comment]
> 
> 
> Hi @nsuchy thanks for the pull request. Ideally I'd like to ditch the magic URL altogether, as indicated by #3. What do you think about that?

You're suggesting we create a config file / initializer system instead?

**Comment by nsuchy** [comment]
Fixed a syntax error in this pull request. I think a good answer to this question starts at whether we have a lot of options in configuration. Right now Mosquito is super simple background task runner. If it gets more features maybe a configuration file will be necessary. I think environment variables are enough for the time being.

**Comment by nsuchy** [comment]
Currently this change looks like it'll require us to use `Mosquito.Base.settings.redis_url` unless I'm misunderstanding something.

**Pull request closed without merging**
