### PR TITLE
Update redis version to support Crystal 0.31.1

### PR DESCRIPTION
**Pull request by nsuchy**
This mege request bumps the version number of redis and supports Crystal 0.31.1.

### CODE REVIEW

**Comment by robacarp** [comment]
@nsuchy thank you!

**Comment by robacarp** [comment]
@nsuchy it looks like minitest had to upgrade to support the new thread stuff, and that's likely why the tests are failing.

**Comment by nsuchy** [comment]
> @nsuchy it looks like minitest had to upgrade to support the new thread stuff, and that's likely why the tests are failing.

Thanks for reviewing this, what changes do I need to make before this can get merged?

**Comment by robacarp** [comment]
@nsuchy update with master and it should pass CI and I'll merge it. Thank you!

**Comment by nsuchy** [comment]
Encountered an error, I'm not familiar enough with this library to understand the output, this part looks relevant though.
```
I, [2019-10-09 18:37:41 +00:00 #616]  INFO -- : Success: task throttled_job<1570646241388:439> finished and took 16.0µs
End of demo.
----------------------------------
Checking integration test flags...
PeriodicallyPuts executed correctly.
QueuedJob executed correctly.
CustomSerializersJob executed correctly.
Unhandled exception: Expected ThrottledJob to have performed 9 times but instead it was performed 8 times. (Exception)
  from demo/run.cr:12:10 in 'expect_run_count'
  from demo/run.cr:39:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
Makefile:11: recipe for target 'demo' failed
make: *** [demo] Error 1
Exited with code 2
```

**Comment by Blacksmoke16** [comment]
@nsuchy Try running it again.  If it fails again, then yea something is prob broken with the throttled jobs.  I'd prob be the most familiar with that...

**Comment by nsuchy** [comment]
@Blacksmoke16 Looks like you or @robacarp beat me to it. It says all checks have passed now. This should be good for merge?

**Comment by robacarp** [comment]
@nsuchy thanks again!

**Pull request merged**
